services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres        # You should modify this
      - POSTGRES_PASSWORD=postgres    # You should modify this
      - POSTGRES_DB=dailymath         # You should modify this
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local